"""
RBL-4 Metrics & Statistics (Them - MS).

Reads:
  - data/<mode>_ground_truth.csv   (annotator_1_*, annotator_2_*, consensus_*)
  - results/<mode>_llm_output.csv  (llm_*_label, raw_json_status)

Computes:
  - Human-Human Cohen's Kappa (annotator_1 vs annotator_2), per component + overall
  - LLM-vs-Developer Cohen's Kappa (llm_*_label vs consensus_*), per component + overall
  - Raw agreement for both
  - Label distribution (consensus vs LLM)
  - N valid / N invalid (raw_json_status != VALID is excluded from LLM-vs-Dev)

Writes:
  - results/summary.csv            (matches existing repo header exactly)
  - results/pilot_analysis_plan.md (pilot mode only)

Run from the REPO ROOT:
  python src/compute_metrics.py --mode pilot
  python src/compute_metrics.py --mode full
"""

import argparse
import csv
from collections import Counter

ALLOWED_LABELS = ["Sufficient", "Ambiguous", "Missing", "Incorrect"]
COMPONENTS = ("OB", "EB", "S2R")

RANGE_MIN = 0.6


def cohen_kappa(pairs):
    pairs = [(a, b) for a, b in pairs if a and b]
    n = len(pairs)
    if n == 0:
        return None
    agree = sum(1 for a, b in pairs if a == b)
    po = agree / n
    count_a = Counter(a for a, _ in pairs)
    count_b = Counter(b for _, b in pairs)
    pe = sum((count_a.get(label, 0) / n) * (count_b.get(label, 0) / n) for label in ALLOWED_LABELS)
    if pe == 1:
        return 1.0 if po == 1 else 0.0
    return (po - pe) / (1 - pe)


def raw_agreement(pairs):
    pairs = [(a, b) for a, b in pairs if a and b]
    if not pairs:
        return None
    return sum(1 for a, b in pairs if a == b) / len(pairs)


def interpret(kappa_value):
    if kappa_value is None:
        return "N/A"
    if kappa_value < 0:
        return "No agreement"
    if kappa_value < 0.2:
        return "Slight"
    if kappa_value < 0.4:
        return "Fair"
    if kappa_value < 0.6:
        return "Moderate"
    if kappa_value < 0.8:
        return "Substantial"
    return "Almost perfect"


def decide(kappa_value):
    if kappa_value is None:
        return "N/A"
    if kappa_value >= RANGE_MIN:
        return "PASS (within accepted range >= 0.6)"
    return "FAIL (< 0.6)"


def read_csv(path):
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_pilot_plan(path, n_valid, n_invalid, hh_kappa, hh_raw, ld_kappa, ld_raw, consensus_dist, llm_dist):
    with open(path, "a", encoding="utf-8") as handle:
        handle.write("\n\n## Computed results (auto-generated by src/compute_metrics.py)\n\n")
        handle.write(f"Mode: `pilot` | N valid: {n_valid} | N invalid: {n_invalid}\n\n")
        handle.write("### Human-Human Kappa\n\n")
        handle.write("| Component | Kappa | Interpretation | Decision |\n|---|---|---|---|\n")
        for component in COMPONENTS:
            kappa_value = hh_kappa[component]
            if kappa_value is not None:
                handle.write(f"| {component} | {kappa_value:.3f} | {interpret(kappa_value)} | {decide(kappa_value)} |\n")
            else:
                handle.write(f"| {component} | N/A | N/A | N/A |\n")
        handle.write(
            f"| **Overall** | {hh_kappa['OVERALL']:.3f} | {interpret(hh_kappa['OVERALL'])} | {decide(hh_kappa['OVERALL'])} |\n"
        )
        handle.write(f"\nRaw agreement: {hh_raw:.3f}\n\n" if hh_raw is not None else "\nRaw agreement: N/A\n\n")

        handle.write("### LLM-vs-Developer Kappa\n\n")
        handle.write("| Component | Kappa | Interpretation | Decision |\n|---|---|---|---|\n")
        for component in COMPONENTS:
            kappa_value = ld_kappa[component]
            if kappa_value is not None:
                handle.write(f"| {component} | {kappa_value:.3f} | {interpret(kappa_value)} | {decide(kappa_value)} |\n")
            else:
                handle.write(f"| {component} | N/A | N/A | N/A |\n")
        handle.write(
            f"| **Overall** | {ld_kappa['OVERALL']:.3f} | {interpret(ld_kappa['OVERALL'])} | {decide(ld_kappa['OVERALL'])} |\n"
        )
        handle.write(f"\nRaw agreement: {ld_raw:.3f}\n\n" if ld_raw is not None else "\nRaw agreement: N/A\n\n")

        handle.write("### Label distribution\n\n")
        handle.write("| Label | Consensus | LLM |\n|---|---|---|\n")
        for label in ALLOWED_LABELS:
            handle.write(f"| {label} | {consensus_dist.get(label, 0)} | {llm_dist.get(label, 0)} |\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["pilot", "full"], default="pilot")
    args = parser.parse_args()

    gt_path = f"data/{args.mode}_ground_truth.csv"
    llm_path = f"results/{args.mode}_llm_output.csv"
    summary_path = "results/summary.csv"
    plan_path = "results/pilot_analysis_plan.md"

    gt_rows = read_csv(gt_path)
    llm_rows = read_csv(llm_path)

    llm_by_key = {(row["repo"], row["issue_id"]): row for row in llm_rows}

    hh_pairs = {component: [] for component in COMPONENTS}
    for row in gt_rows:
        hh_pairs["OB"].append((row["annotator_1_ob"], row["annotator_2_ob"]))
        hh_pairs["EB"].append((row["annotator_1_eb"], row["annotator_2_eb"]))
        hh_pairs["S2R"].append((row["annotator_1_s2r"], row["annotator_2_s2r"]))

    hh_overall_pairs = hh_pairs["OB"] + hh_pairs["EB"] + hh_pairs["S2R"]

    ld_pairs = {component: [] for component in COMPONENTS}
    n_invalid = 0
    n_valid = 0
    consensus_dist = Counter()
    llm_dist = Counter()

    for row in gt_rows:
        key = (row["repo"], row["issue_id"])
        llm_row = llm_by_key.get(key)
        if llm_row is None or llm_row.get("raw_json_status") != "VALID":
            n_invalid += 1
            continue
        n_valid += 1
        pairs = [
            ("OB", row["consensus_ob"], llm_row.get("llm_ob_label", "")),
            ("EB", row["consensus_eb"], llm_row.get("llm_eb_label", "")),
            ("S2R", row["consensus_s2r"], llm_row.get("llm_s2r_label", "")),
        ]
        for component, consensus_value, llm_value in pairs:
            ld_pairs[component].append((consensus_value, llm_value))
            if consensus_value:
                consensus_dist[consensus_value] += 1
            if llm_value:
                llm_dist[llm_value] += 1

    ld_overall_pairs = ld_pairs["OB"] + ld_pairs["EB"] + ld_pairs["S2R"]

    hh_kappa = {component: cohen_kappa(hh_pairs[component]) for component in COMPONENTS}
    hh_kappa["OVERALL"] = cohen_kappa(hh_overall_pairs)
    hh_raw = raw_agreement(hh_overall_pairs)

    ld_kappa = {component: cohen_kappa(ld_pairs[component]) for component in COMPONENTS}
    ld_kappa["OVERALL"] = cohen_kappa(ld_overall_pairs)
    ld_raw = raw_agreement(ld_overall_pairs)

    print(f"=== RBL-4 Metrics ({args.mode}) ===")
    print(f"N ground-truth rows: {len(gt_rows)}")
    print(f"N valid (LLM VALID + matched): {n_valid}")
    print(f"N invalid / skipped: {n_invalid}\n")

    print("-- Human-Human Kappa --")
    for component in COMPONENTS:
        kappa_value = hh_kappa[component]
        if kappa_value is not None:
            print(f"  {component}: {kappa_value:.3f} ({interpret(kappa_value)}) -> {decide(kappa_value)}")
        else:
            print(f"  {component}: N/A")
    print(f"  Overall: {hh_kappa['OVERALL']:.3f} ({interpret(hh_kappa['OVERALL'])}) -> {decide(hh_kappa['OVERALL'])}")
    print(f"  Raw agreement: {hh_raw:.3f}\n" if hh_raw is not None else "  Raw agreement: N/A\n")

    print("-- LLM vs Developer Kappa --")
    for component in COMPONENTS:
        kappa_value = ld_kappa[component]
        if kappa_value is not None:
            print(f"  {component}: {kappa_value:.3f} ({interpret(kappa_value)}) -> {decide(kappa_value)}")
        else:
            print(f"  {component}: N/A")
    print(f"  Overall: {ld_kappa['OVERALL']:.3f} ({interpret(ld_kappa['OVERALL'])}) -> {decide(ld_kappa['OVERALL'])}")
    print(f"  Raw agreement: {ld_raw:.3f}\n" if ld_raw is not None else "  Raw agreement: N/A\n")

    print("-- Label distribution (consensus) --")
    for label in ALLOWED_LABELS:
        print(f"  {label}: {consensus_dist.get(label, 0)}")
    print("-- Label distribution (LLM) --")
    for label in ALLOWED_LABELS:
        print(f"  {label}: {llm_dist.get(label, 0)}")

    summary_rows = [
        ("ms-hh-kappa-overall", "human_human_kappa_overall", hh_kappa["OVERALL"], "", "", n_valid, n_invalid, decide(hh_kappa["OVERALL"])),
        ("ms-hh-kappa-ob", "human_human_kappa_ob", hh_kappa["OB"], "", "", n_valid, n_invalid, decide(hh_kappa["OB"])),
        ("ms-hh-kappa-eb", "human_human_kappa_eb", hh_kappa["EB"], "", "", n_valid, n_invalid, decide(hh_kappa["EB"])),
        ("ms-hh-kappa-s2r", "human_human_kappa_s2r", hh_kappa["S2R"], "", "", n_valid, n_invalid, decide(hh_kappa["S2R"])),
        ("ms-hh-raw-agreement", "human_human_raw_agreement", hh_raw, "", "", n_valid, n_invalid, ""),
        ("ms-llm-dev-kappa-overall", "llm_dev_kappa_overall", ld_kappa["OVERALL"], "", "", n_valid, n_invalid, decide(ld_kappa["OVERALL"])),
        ("ms-llm-dev-kappa-ob", "llm_dev_kappa_ob", ld_kappa["OB"], "", "", n_valid, n_invalid, decide(ld_kappa["OB"])),
        ("ms-llm-dev-kappa-eb", "llm_dev_kappa_eb", ld_kappa["EB"], "", "", n_valid, n_invalid, decide(ld_kappa["EB"])),
        ("ms-llm-dev-kappa-s2r", "llm_dev_kappa_s2r", ld_kappa["S2R"], "", "", n_valid, n_invalid, decide(ld_kappa["S2R"])),
        ("ms-llm-dev-raw-agreement", "llm_dev_raw_agreement", ld_raw, "", "", n_valid, n_invalid, ""),
    ]

    with open(summary_path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["rq_name", "metric_name", "metric_value", "p_value", "effect_size", "n_valid", "n_invalid", "decision"])
        for rq_name, metric_name, value, p_value, effect_size, valid_count, invalid_count, decision in summary_rows:
            value_str = f"{value:.4f}" if isinstance(value, float) else (value if value is not None else "")
            writer.writerow([rq_name, metric_name, value_str, p_value, effect_size, valid_count, invalid_count, decision])

    print(f"\nWrote {summary_path}")

    if args.mode == "pilot":
        write_pilot_plan(plan_path, n_valid, n_invalid, hh_kappa, hh_raw, ld_kappa, ld_raw, consensus_dist, llm_dist)
        print(f"Appended computed results to {plan_path}")
    else:
        print("Full mode: skipped writing to pilot_analysis_plan.md")


if __name__ == "__main__":
    main()
